"""ocr_and_vision_tables

Revision ID: 31f7ac7d8d9a
Revises: e7b8c9d0a1f2
Create Date: 2026-03-01 03:54:42.005650

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "31f7ac7d8d9a"
down_revision: Union[str, None] = "e7b8c9d0a1f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_table(
        "ocr_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("image_path", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("raw_ocr_text", sa.Text(), nullable=True),
        sa.Column("extracted_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.store_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vision_category_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("tag", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ocr_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ocr_job_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("raw_text", sa.String(length=256), nullable=True),
        sa.Column("matched_product_id", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ocr_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matched_product_id"],
            ["products.product_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Removed unrelated changes
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed unrelated changes
    op.drop_table("ocr_job_items")
    op.drop_table("vision_category_tags")
    op.drop_table("ocr_jobs")
    # ### end Alembic commands ###
