"""staff_performance

Revision ID: 6cd27932870e
Revises: b4g02e3d6c99
Create Date: 2026-02-28 04:04:19.663676

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cd27932870e"
down_revision: Union[str, None] = "b4g02e3d6c99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff_daily_targets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("revenue_target", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("transaction_count_target", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.store_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "user_id", "target_date", name="uq_staff_daily_target_store_user_date"),
    )
    op.create_table(
        "staff_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("ended_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="OPEN", nullable=False),
        sa.Column("target_revenue", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.store_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("transactions", sa.Column("session_id", sa.UUID(), nullable=True))
    op.create_index("idx_transactions_session_id", "transactions", ["session_id"], unique=False)
    op.create_foreign_key("fk_transactions_session_id", "transactions", "staff_sessions", ["session_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_transactions_session_id", "transactions", type_="foreignkey")
    op.drop_index("idx_transactions_session_id", table_name="transactions")
    op.drop_column("transactions", "session_id")
    op.drop_table("staff_sessions")
    op.drop_table("staff_daily_targets")
    # ### end Alembic commands ###
