"""security_and_mfa

Revision ID: 7f8e9a0b1c2d
Revises: eb7c8d9e0f1a
Create Date: 2026-03-10 19:10:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f8e9a0b1c2d"
down_revision: Union[str, None] = "eb7c8d9e0f1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("mfa_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("users", sa.Column("mfa_secret", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("last_login_at", sa.TIMESTAMP(), nullable=True))
    op.add_column(
        "users", sa.Column("failed_login_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False)
    )
    op.add_column("users", sa.Column("locked_until", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failed_login_attempts")
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "mfa_secret")
    op.drop_column("users", "mfa_enabled")
    # ### end Alembic commands ###
