"""auto

Revision ID: 85d1654fde0f
Revises: f4a5b6c7d8e9
Create Date: 2026-03-02 16:21:54.825770

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85d1654fde0f"
down_revision: Union[str, None] = "f4a5b6c7d8e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type for postgres explicitly before using it
    gender_enum = sa.Enum("male", "female", "other", name="customer_gender_enum")
    gender_enum.create(op.get_bind(), checkfirst=True)

    op.drop_index("idx_business_events_store_id", table_name="business_events")
    op.drop_index("idx_chain_daily_aggregates_group_id", table_name="chain_daily_aggregates")
    op.drop_index("idx_chain_daily_aggregates_store_id", table_name="chain_daily_aggregates")
    op.alter_column(
        "credit_transactions",
        "type",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column("credit_transactions", "amount", existing_type=sa.NUMERIC(precision=12, scale=2), nullable=False)
    op.alter_column(
        "credit_transactions", "balance_after", existing_type=sa.NUMERIC(precision=12, scale=2), nullable=False
    )
    op.alter_column("credit_transactions", "notes", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
    op.drop_index("idx_credit_transactions_ledger_id", table_name="credit_transactions")
    op.drop_index("idx_credit_transactions_transaction_id", table_name="credit_transactions")
    op.add_column(
        "customers", sa.Column("gender", sa.Enum("male", "female", "other", name="customer_gender_enum"), nullable=True)
    )
    op.add_column("customers", sa.Column("birth_date", sa.Date(), nullable=True))
    op.drop_index("idx_demand_sensing_log_product_id", table_name="demand_sensing_log")
    op.drop_index("idx_demand_sensing_log_store_id", table_name="demand_sensing_log")
    op.drop_index("idx_event_impact_actuals_event_id", table_name="event_impact_actuals")
    op.drop_index("idx_event_impact_actuals_product_id", table_name="event_impact_actuals")
    op.add_column("forecast_cache", sa.Column("model_type", sa.String(length=30), nullable=True))
    op.add_column("forecast_cache", sa.Column("training_window_days", sa.Integer(), nullable=True))
    op.create_unique_constraint(
        "uq_forecast_cache_store_product_date", "forecast_cache", ["store_id", "product_id", "forecast_date"]
    )
    op.drop_index("idx_goods_receipt_notes_po_id", table_name="goods_receipt_notes")
    op.drop_index("idx_goods_receipt_notes_received_by", table_name="goods_receipt_notes")
    op.drop_index("idx_goods_receipt_notes_store_id", table_name="goods_receipt_notes")
    op.drop_index("idx_gst_transactions_store_period", table_name="gst_transactions")
    op.drop_index("idx_inter_store_transfer_from_store", table_name="inter_store_transfer_suggestions")
    op.drop_index("idx_inter_store_transfer_group_id", table_name="inter_store_transfer_suggestions")
    op.drop_index("idx_inter_store_transfer_product", table_name="inter_store_transfer_suggestions")
    op.drop_index("idx_inter_store_transfer_to_store", table_name="inter_store_transfer_suggestions")
    op.alter_column(
        "loyalty_programs",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.drop_index("idx_loyalty_transactions_account_id", table_name="loyalty_transactions")
    op.drop_index("idx_loyalty_transactions_transaction_id", table_name="loyalty_transactions")
    op.drop_index("idx_ocr_job_items_job_id", table_name="ocr_job_items")
    op.drop_index("idx_ocr_job_items_matched_product_id", table_name="ocr_job_items")
    op.drop_index("idx_ocr_jobs_store_id", table_name="ocr_jobs")
    op.drop_index("idx_product_price_history_changed_by", table_name="product_price_history")
    op.drop_index("idx_product_price_history_product_id", table_name="product_price_history")
    op.drop_index("idx_product_price_history_store_id", table_name="product_price_history")
    op.drop_index("idx_purchase_order_items_po_id", table_name="purchase_order_items")
    op.drop_index("idx_purchase_order_items_product_id", table_name="purchase_order_items")
    op.drop_index("idx_purchase_orders_created_by", table_name="purchase_orders")
    op.drop_index("idx_purchase_orders_supplier_id", table_name="purchase_orders")
    op.drop_index("idx_stock_adjustments_adjusted_by", table_name="stock_adjustments")
    op.drop_index("idx_stock_adjustments_product_id", table_name="stock_adjustments")
    op.drop_index("idx_stock_audit_items_audit_id", table_name="stock_audit_items")
    op.drop_index("idx_stock_audit_items_product_id", table_name="stock_audit_items")
    op.drop_index("idx_store_group_memberships_group_id", table_name="store_group_memberships")
    op.drop_index("idx_store_group_memberships_store_id", table_name="store_group_memberships")
    op.drop_index("idx_supplier_products_product_id", table_name="supplier_products")
    op.drop_index("idx_supplier_products_supplier_id", table_name="supplier_products")
    op.drop_index("idx_vision_category_tags_job_id", table_name="vision_category_tags")
    op.drop_index("idx_whatsapp_message_log_store_id", table_name="whatsapp_message_log")
    op.drop_index("idx_whatsapp_templates_store_id", table_name="whatsapp_templates")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_whatsapp_templates_store_id", "whatsapp_templates", ["store_id"], unique=False)
    op.create_index("idx_whatsapp_message_log_store_id", "whatsapp_message_log", ["store_id"], unique=False)
    op.create_index("idx_vision_category_tags_job_id", "vision_category_tags", ["job_id"], unique=False)
    op.create_index("idx_supplier_products_supplier_id", "supplier_products", ["supplier_id"], unique=False)
    op.create_index("idx_supplier_products_product_id", "supplier_products", ["product_id"], unique=False)
    op.create_index("idx_store_group_memberships_store_id", "store_group_memberships", ["store_id"], unique=False)
    op.create_index("idx_store_group_memberships_group_id", "store_group_memberships", ["group_id"], unique=False)
    op.create_index("idx_stock_audit_items_product_id", "stock_audit_items", ["product_id"], unique=False)
    op.create_index("idx_stock_audit_items_audit_id", "stock_audit_items", ["audit_id"], unique=False)
    op.create_index("idx_stock_adjustments_product_id", "stock_adjustments", ["product_id"], unique=False)
    op.create_index("idx_stock_adjustments_adjusted_by", "stock_adjustments", ["adjusted_by"], unique=False)
    op.create_index("idx_purchase_orders_supplier_id", "purchase_orders", ["supplier_id"], unique=False)
    op.create_index("idx_purchase_orders_created_by", "purchase_orders", ["created_by"], unique=False)
    op.create_index("idx_purchase_order_items_product_id", "purchase_order_items", ["product_id"], unique=False)
    op.create_index("idx_purchase_order_items_po_id", "purchase_order_items", ["po_id"], unique=False)
    op.create_index("idx_product_price_history_store_id", "product_price_history", ["store_id"], unique=False)
    op.create_index("idx_product_price_history_product_id", "product_price_history", ["product_id"], unique=False)
    op.create_index("idx_product_price_history_changed_by", "product_price_history", ["changed_by"], unique=False)
    op.create_index("idx_ocr_jobs_store_id", "ocr_jobs", ["store_id"], unique=False)
    op.create_index("idx_ocr_job_items_matched_product_id", "ocr_job_items", ["matched_product_id"], unique=False)
    op.create_index("idx_ocr_job_items_job_id", "ocr_job_items", ["job_id"], unique=False)
    op.create_index("idx_loyalty_transactions_transaction_id", "loyalty_transactions", ["transaction_id"], unique=False)
    op.create_index("idx_loyalty_transactions_account_id", "loyalty_transactions", ["account_id"], unique=False)
    op.alter_column(
        "loyalty_programs",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.create_index(
        "idx_inter_store_transfer_to_store", "inter_store_transfer_suggestions", ["to_store_id"], unique=False
    )
    op.create_index(
        "idx_inter_store_transfer_product", "inter_store_transfer_suggestions", ["product_id"], unique=False
    )
    op.create_index("idx_inter_store_transfer_group_id", "inter_store_transfer_suggestions", ["group_id"], unique=False)
    op.create_index(
        "idx_inter_store_transfer_from_store", "inter_store_transfer_suggestions", ["from_store_id"], unique=False
    )
    op.create_index("idx_gst_transactions_store_period", "gst_transactions", ["store_id", "period"], unique=False)
    op.create_index("idx_goods_receipt_notes_store_id", "goods_receipt_notes", ["store_id"], unique=False)
    op.create_index("idx_goods_receipt_notes_received_by", "goods_receipt_notes", ["received_by"], unique=False)
    op.create_index("idx_goods_receipt_notes_po_id", "goods_receipt_notes", ["po_id"], unique=False)
    op.drop_constraint("uq_forecast_cache_store_product_date", "forecast_cache", type_="unique")
    op.drop_column("forecast_cache", "training_window_days")
    op.drop_column("forecast_cache", "model_type")
    op.create_index("idx_event_impact_actuals_product_id", "event_impact_actuals", ["product_id"], unique=False)
    op.create_index("idx_event_impact_actuals_event_id", "event_impact_actuals", ["event_id"], unique=False)
    op.create_index("idx_demand_sensing_log_store_id", "demand_sensing_log", ["store_id"], unique=False)
    op.create_index("idx_demand_sensing_log_product_id", "demand_sensing_log", ["product_id"], unique=False)
    op.drop_column("customers", "birth_date")
    op.drop_column("customers", "gender")
    # Drop the enum type for postgres explicitly after dropping the column
    gender_enum = sa.Enum("male", "female", "other", name="customer_gender_enum")
    gender_enum.drop(op.get_bind(), checkfirst=True)
    op.create_index("idx_credit_transactions_transaction_id", "credit_transactions", ["transaction_id"], unique=False)
    op.create_index("idx_credit_transactions_ledger_id", "credit_transactions", ["ledger_id"], unique=False)
    op.alter_column("credit_transactions", "notes", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
    op.alter_column(
        "credit_transactions", "balance_after", existing_type=sa.NUMERIC(precision=12, scale=2), nullable=True
    )
    op.alter_column("credit_transactions", "amount", existing_type=sa.NUMERIC(precision=12, scale=2), nullable=True)
    op.alter_column(
        "credit_transactions",
        "type",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.create_index("idx_chain_daily_aggregates_store_id", "chain_daily_aggregates", ["store_id"], unique=False)
    op.create_index("idx_chain_daily_aggregates_group_id", "chain_daily_aggregates", ["group_id"], unique=False)
    op.create_index("idx_business_events_store_id", "business_events", ["store_id"], unique=False)
    # ### end Alembic commands ###
