"""whatsapp_integration

Revision ID: b966c53b0061
Revises: 908d85de1d01
Create Date: 2026-02-28 16:20:15.548727

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b966c53b0061"
down_revision: Union[str, None] = "908d85de1d01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatsapp_config",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("phone_number_id", sa.String(length=64), nullable=True),
        sa.Column("access_token_encrypted", sa.Text(), nullable=True),
        sa.Column("webhook_verify_token", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("waba_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.store_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id"),
    )
    op.create_table(
        "whatsapp_message_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("recipient_phone", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=8), server_default="OUT", nullable=False),
        sa.Column("message_type", sa.String(length=32), nullable=False),
        sa.Column("template_name", sa.String(length=128), nullable=True),
        sa.Column("content_preview", sa.Text(), nullable=True),
        sa.Column("wa_message_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="QUEUED", nullable=False),
        sa.Column("sent_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("delivered_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.store_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "whatsapp_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("template_name", sa.String(length=128), nullable=False),
        sa.Column("template_category", sa.String(length=32), nullable=True),
        sa.Column("language", sa.String(length=10), server_default="en", nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.store_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("whatsapp_templates")
    op.drop_table("whatsapp_message_log")
    op.drop_table("whatsapp_config")
    # ### end Alembic commands ###
