"""align loan applications model drift

Revision ID: ef7d1bae1e6e
Revises: 4e4dc5144eb4
Create Date: 2026-03-17 23:41:25.064682

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = "ef7d1bae1e6e"
down_revision: Union[str, None] = "4e4dc5144eb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum type if it doesn't exist (Postgres-specific)
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'merchant_kyc_status_enum') THEN CREATE TYPE merchant_kyc_status_enum AS ENUM ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED'); END IF; END $$;"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("forecast_horizon_days", sa.Integer(), nullable=False),
        sa.Column("granularity", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.store_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_regressors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("config_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("prior_scale", sa.Float(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["forecast_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financial_accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_number", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("ifsc_code", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("bank_name", sa.String(length=128), nullable=True))
        batch_op.drop_constraint("uq_store_account_type", type_="unique")
        batch_op.drop_column("account_name")
        batch_op.drop_column("currency")

    with op.batch_alter_table("insurance_claims", schema=None) as batch_op:
        batch_op.add_column(sa.Column("claim_amount", sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column("approved_amount", sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("submitted_at", sa.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column("resolved_at", sa.TIMESTAMP(), nullable=True))
        batch_op.drop_column("paid_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("trigger_type")
        batch_op.drop_column("payout_amount")

    with op.batch_alter_table("insurance_policies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("policy_number", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("premium_amount", sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column("coverage_amount", sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column("start_date", sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column("end_date", sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
        batch_op.create_unique_constraint("uq_insurance_policy_number", ["policy_number"])
        batch_op.drop_column("enrolled_at")
        batch_op.drop_column("expires_at")

    with op.batch_alter_table("insurance_products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("product_type", sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column("provider", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("premium_rate", sa.Numeric(precision=5, scale=4), nullable=True))
        batch_op.add_column(sa.Column("coverage_amount", sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
        batch_op.drop_column("premium_monthly")
        batch_op.drop_column("category")
        batch_op.drop_column("max_coverage")

    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_ledger_entries_transaction_id")
        batch_op.add_column(sa.Column("balance_after", sa.Numeric(precision=14, scale=2), nullable=False))
        batch_op.add_column(sa.Column("reference_id", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("reference_type", sa.String(length=64), nullable=True))
        batch_op.drop_column("meta_data")
        batch_op.drop_column("currency")
        batch_op.drop_column("transaction_id")

    with op.batch_alter_table("loan_applications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("loan_product_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("tenure_days", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("interest_rate", sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column("purpose", sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column("rejection_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("disbursed_at", sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column("due_date", sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column("interest_recalculated_at", sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
        batch_op.create_foreign_key("fk_loan_app_loan_product", "loan_products", ["loan_product_id"], ["id"])
        batch_op.drop_column("disbursement_date")
        batch_op.drop_column("interest_rate_at_origination")
        batch_op.drop_column("term_days")
        batch_op.drop_column("product_id")
        batch_op.drop_column("applied_at")

    with op.batch_alter_table("loan_products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("min_tenure_days", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("max_tenure_days", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("base_interest_rate", sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column("processing_fee_pct", sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column("eligibility_criteria", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
        batch_op.drop_column("interest_rate_bps")
        batch_op.drop_column("max_term_days")

    with op.batch_alter_table("loan_repayments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("loan_application_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("payment_mode", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("reference_number", sa.String(length=128), nullable=True))
        batch_op.alter_column("principal_component", existing_type=sa.NUMERIC(precision=14, scale=2), nullable=True)
        batch_op.alter_column("interest_component", existing_type=sa.NUMERIC(precision=14, scale=2), nullable=True)
        batch_op.create_foreign_key("fk_loan_repayment_app", "loan_applications", ["loan_application_id"], ["id"])
        batch_op.drop_column("loan_id")
        batch_op.drop_column("ledger_transaction_id")

    with op.batch_alter_table("merchant_credit_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("credit_limit", sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column("utilization_pct", sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column("history", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("last_evaluated_at", sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
        batch_op.alter_column("credit_score", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("last_recalculated", existing_type=sa.TIMESTAMP(), nullable=True)
        batch_op.drop_column("scoring_version")

    with op.batch_alter_table("merchant_kyc", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "kyc_status",
                sa.Enum("PENDING", "VERIFIED", "REJECTED", "EXPIRED", name="merchant_kyc_status_enum"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("verified_at", sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column("documents", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
        batch_op.alter_column("verification_status", existing_type=sa.VARCHAR(length=8), nullable=True)
        batch_op.drop_column("verification_date")

    # Separate drops and adds for SQLite batch mode stability on payment_transactions
    with op.batch_alter_table("payment_transactions", schema=None) as batch_op:
        batch_op.drop_column("transaction_id")
        batch_op.drop_column("external_id")
        batch_op.drop_column("payment_method")

    with op.batch_alter_table("payment_transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("currency", sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column("payment_mode", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("gateway", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("gateway_txn_id", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("metadata", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("transaction_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("external_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("payment_method", sa.String(length=32), nullable=True))
        batch_op.alter_column(
            "fees",
            existing_type=sa.NUMERIC(precision=12, scale=2),
            type_=sa.Numeric(precision=14, scale=2),
            nullable=True,
        )

    with op.batch_alter_table("treasury_configs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sweep_enabled", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("sweep_threshold", sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column("sweep_target_account_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
        batch_op.alter_column("sweep_strategy", existing_type=sa.VARCHAR(length=12), nullable=True)
        batch_op.alter_column("min_balance_threshold", existing_type=sa.NUMERIC(precision=14, scale=2), nullable=True)
        batch_op.create_foreign_key(
            "fk_treasury_config_target", "financial_accounts", ["sweep_target_account_id"], ["id"]
        )
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("treasury_transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("config_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("transaction_type", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("status", sa.String(length=32), nullable=False))
        batch_op.alter_column("store_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("type", existing_type=sa.VARCHAR(length=13), nullable=True)
        batch_op.create_foreign_key("fk_treasury_transaction_config", "treasury_configs", ["config_id"], ["id"])

    with op.batch_alter_table("webhook_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_error", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhook_events", schema=None) as batch_op:
        batch_op.drop_column("last_error")

    with op.batch_alter_table("treasury_transactions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("type", existing_type=sa.VARCHAR(length=13), nullable=False)
        batch_op.alter_column("store_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("status")
        batch_op.drop_column("transaction_type")
        batch_op.drop_column("config_id")

    with op.batch_alter_table("treasury_configs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.TIMESTAMP(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("min_balance_threshold", existing_type=sa.NUMERIC(precision=14, scale=2), nullable=False)
        batch_op.alter_column("sweep_strategy", existing_type=sa.VARCHAR(length=12), nullable=False)
        batch_op.drop_column("created_at")
        batch_op.drop_column("sweep_target_account_id")
        batch_op.drop_column("sweep_threshold")
        batch_op.drop_column("sweep_enabled")

    with op.batch_alter_table("payment_transactions", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "transactions", ["transaction_id"], ["transaction_id"])
        batch_op.alter_column("fees", existing_type=sa.NUMERIC(precision=12, scale=2), nullable=False)
        batch_op.drop_column("metadata")
        batch_op.drop_column("gateway_txn_id")
        batch_op.drop_column("gateway")
        batch_op.drop_column("payment_mode")
        batch_op.drop_column("currency")

    with op.batch_alter_table("merchant_kyc", schema=None) as batch_op:
        batch_op.add_column(sa.Column("verification_date", sa.TIMESTAMP(), nullable=True))
        batch_op.alter_column("verification_status", existing_type=sa.VARCHAR(length=8), nullable=False)
        batch_op.drop_column("created_at")
        batch_op.drop_column("documents")
        batch_op.drop_column("verified_at")
        batch_op.drop_column("kyc_status")

    with op.batch_alter_table("merchant_credit_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scoring_version", sa.VARCHAR(length=16), nullable=True))
        batch_op.alter_column("last_recalculated", existing_type=sa.TIMESTAMP(), nullable=False)
        batch_op.alter_column("credit_score", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("created_at")
        batch_op.drop_column("last_evaluated_at")
        batch_op.drop_column("history")
        batch_op.drop_column("utilization_pct")
        batch_op.drop_column("credit_limit")

    with op.batch_alter_table("loan_repayments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ledger_transaction_id", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("loan_id", sa.BIGINT(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "loan_applications", ["loan_id"], ["id"])
        batch_op.alter_column("interest_component", existing_type=sa.NUMERIC(precision=14, scale=2), nullable=False)
        batch_op.alter_column("principal_component", existing_type=sa.NUMERIC(precision=14, scale=2), nullable=False)
        batch_op.drop_column("reference_number")
        batch_op.drop_column("payment_mode")
        batch_op.drop_column("loan_application_id")

    with op.batch_alter_table("loan_products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("max_term_days", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("interest_rate_bps", sa.INTEGER(), nullable=False))
        batch_op.drop_column("created_at")
        batch_op.drop_column("eligibility_criteria")
        batch_op.drop_column("processing_fee_pct")
        batch_op.drop_column("base_interest_rate")
        batch_op.drop_column("max_tenure_days")
        batch_op.drop_column("min_tenure_days")

    with op.batch_alter_table("loan_applications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("applied_at", sa.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column("product_id", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("term_days", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("interest_rate_at_origination", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("disbursement_date", sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "loan_products", ["product_id"], ["id"])
        batch_op.drop_column("created_at")
        batch_op.drop_column("interest_recalculated_at")
        batch_op.drop_column("due_date")
        batch_op.drop_column("disbursed_at")
        batch_op.drop_column("rejection_reason")
        batch_op.drop_column("purpose")
        batch_op.drop_column("interest_rate")
        batch_op.drop_column("tenure_days")
        batch_op.drop_column("loan_product_id")

    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("transaction_id", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("currency", sa.VARCHAR(length=3), nullable=False))
        batch_op.add_column(sa.Column("meta_data", sa.JSON(), nullable=True))
        batch_op.drop_column("reference_type")
        batch_op.drop_column("reference_id")
        batch_op.drop_column("balance_after")

    with op.batch_alter_table("insurance_products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("max_coverage", sa.NUMERIC(precision=14, scale=2), nullable=False))
        batch_op.add_column(sa.Column("category", sa.VARCHAR(length=12), nullable=False))
        batch_op.add_column(sa.Column("premium_monthly", sa.NUMERIC(precision=12, scale=2), nullable=False))
        batch_op.drop_column("created_at")
        batch_op.drop_column("coverage_amount")
        batch_op.drop_column("premium_rate")
        batch_op.drop_column("provider")
        batch_op.drop_column("product_type")

    with op.batch_alter_table("insurance_policies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("expires_at", sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column("enrolled_at", sa.TIMESTAMP(), nullable=False))
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("created_at")
        batch_op.drop_column("is_active")
        batch_op.drop_column("end_date")
        batch_op.drop_column("start_date")
        batch_op.drop_column("coverage_amount")
        batch_op.drop_column("premium_amount")
        batch_op.drop_column("policy_number")

    with op.batch_alter_table("insurance_claims", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payout_amount", sa.NUMERIC(precision=14, scale=2), nullable=False))
        batch_op.add_column(sa.Column("trigger_type", sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column("paid_at", sa.TIMESTAMP(), nullable=True))
        batch_op.drop_column("resolved_at")
        batch_op.drop_column("submitted_at")
        batch_op.drop_column("description")
        batch_op.drop_column("approved_amount")
        batch_op.drop_column("claim_amount")

    with op.batch_alter_table("financial_accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("currency", sa.VARCHAR(length=3), nullable=False))
        batch_op.add_column(sa.Column("account_name", sa.VARCHAR(length=64), nullable=False))
        batch_op.create_unique_constraint("uq_store_account_type", ["store_id", "account_type"])
        batch_op.drop_column("bank_name")
        batch_op.drop_column("ifsc_code")
        batch_op.drop_column("account_number")

    op.drop_table("event_regressors")
    op.drop_table("forecast_configs")

    # Drop enum type
    op.execute("DROP TYPE IF EXISTS merchant_kyc_status_enum")
    # ### end Alembic commands ###
